### ISSUE TITLE
Code style guide

### ISSUE THREAD

**Issue by mbernson** [y0sh1/ipsen1-quarto#2]
Hallo allemaal,

Ik heb op de project-wiki een pagina met richtlijnen voor de code van dit project geschreven: https://github.com/y0sh1/ipsen1-quarto/wiki/Quarto-Java-style-guide

Aangezien het de bedoeling is dat we ons hier allemaal aan houden hoor ik graag hoe jullie erover denken.

Als iedereen akkoord is met de richtlijnen kan dit issue gesloten worden.

**Comment by y0sh1** [comment]
Ik vindt dit goed.
