### ISSUE TITLE
Knop Instructies

### ISSUE THREAD

**Issue by y0sh1** [y0sh1/ipsen1-quarto#20]
Ik heb een probleem in branch LeesInstructies.

De knop staat strak tegen de onderkant, eigenlijk wil ik wat ruimte tussen de onderkant knop en border van het frame, kan dit?

**Comment by mbernson** [comment]
Ik zie nog geen knop, is hij wel gepusht?

![screen shot 2014-04-20 at 09 17 42](https://cloud.githubusercontent.com/assets/477710/2750212/faaa77e8-c85b-11e3-8cb6-b528d64edbb4.png)

**Comment by y0sh1** [comment]
Bij mij ziet het er nu zo uit,

![instructies](https://cloud.githubusercontent.com/assets/1150960/2750454/c5f52b40-c87b-11e3-907a-5bf2cf196341.png)

**Comment by mbernson** [comment]
Dit moet denk ik nog netter worden.

**Comment by mbernson** [comment]
Wie pakt dit op?

**Comment by mbernson** [comment]
Opgelost door 178daa2b6ca48
