### ISSUE TITLE
System.out.println()'s verwijderen

### ISSUE THREAD

**Issue by mbernson** [y0sh1/ipsen1-quarto#27]
Moet gebeuren voor de oplevering.

**Comment by mbernson** [comment]
Ook elke e.printStackTrace(), die moeten op een fatsoenlijke manier worden afgehandeld. :wink:

**Comment by y0sh1** [comment]
Hier op wachten tot het einde

**Comment by mbernson** [comment]
Allemaal opgelost. :smiley:
