### ISSUE TITLE
Bord UI problemen fixen

### ISSUE THREAD

**Issue by mbernson** [y0sh1/ipsen1-quarto#28]
Het bord ziet er onder Windows nog verschrikkelijk uit. Op de Mac zijn de pionnen ook nog niet mooi gecentreerd.

**Comment by mbernson** [comment]
Ergste is nu achter de rug, maar de vlakjes zijn nog niet volledig klikbaar.

**Comment by y0sh1** [comment]
Gerepareerd door @Timmehj . @Timmehj maakt hiervoor een pull request hiervoor.
