### ISSUE TITLE
Opslaan spel

### ISSUE THREAD

**Issue by mbernson** [y0sh1/ipsen1-quarto#6]
Beschrijving van het opslaan van het spel Quarto! tijdens het spelen.

**Comment by y0sh1** [comment]
In verband met tijd neem ik spel opslaan over

**Comment by y0sh1** [comment]
Opslaan gaat nu enigsinds, geeft alleen exception. @duckson kijkt hier verder naar

**Comment by timvane** [comment]
Spel opslaan is afgerond.

**Comment by mbernson** [comment]
Hebben jullie 'm allebei getest @y0sh1 en @Timmehj ?
